name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Print Node.js and package versions
        run: |
          node --version
          yarn --version
          yarn list @next/mdx @mdx-js/loader @mdx-js/react remark-gfm rehype-prism-plus rehype-preset-minify

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: yarn install

      - name: Build with Next.js
        run: yarn next build

      - name: Export Next.js static site
        run: yarn next export

      - name: Copy public folder
        run: cp -R public .next/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./.next

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ./.next

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Deploy to GitHub Pages
        run: |
          cd ./.next
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M main
          git push -f https://github.com/${{ github.repository }}.git main:gh-pages

      - name: Set Environment URL
        run: echo "URL=https://${{ github.repository_owner }}.github.io/${{ github.repository }}" >> $GITHUB_ENV
